# Default values for baneks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
labels:
  app: banks-backend

namespace: banks

replicaCount: 1

image:
  repository: maxsurm/banks
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  letsencrypt: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: banks.ranus.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - banks.ranus.xyz
      secretName: tls-banks-ingress-http

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 12Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
